# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=20)),
                ('aads', models.CharField(max_length=255)),
                ('aphone', models.CharField(max_length=11)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('show_address', '查看地址管理'), ('insert_address', '添加地址'), ('edit_address', '修改地址'), ('del_address', '删除地址')),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('storage', models.IntegerField()),
                ('pic', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('num', models.IntegerField(default=0)),
                ('clicknum', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('show_goods', '查看商品管理'), ('insert_goods', '添加商品'), ('edit_goods', '修改商品'), ('del_goods', '删除商品')),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.FloatField()),
                ('totalnum', models.IntegerField()),
                ('status', models.IntegerField()),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Address')),
            ],
            options={
                'permissions': (('show_order', '查看订单管理'), ('insert_order', '添加订单'), ('edit_order', '修改订单'), ('del_order', '删除订单')),
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('path', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('show_types', '查看商品分类管理'), ('insert_types', '添加商品分类'), ('edit_types', '修改商品分类'), ('del_types', '删除商品分类')),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=77)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('picurl', models.CharField(default='/static/pics/default/default.jpg', max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('show_users', '查看会员管理'), ('insert_users', '添加会员'), ('edit_users', '修改会员'), ('del_users', '删除会员')),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
        migrations.AddField(
            model_name='goods',
            name='typeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Types'),
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
    ]
